name: API Tests

on:
  push:
    branches:
      - main

jobs:
  api-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: API

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Executar testes de API
        run: npm test 